---
- name: Ensure PPS, UART, and radio disable overlays are configured in /boot/firmware/config.txt
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: EOF
  loop:
    - { regexp: '^#?dtoverlay=pps-gpio', line: 'dtoverlay=pps-gpio,gpiopin=18' }
    - { regexp: '^#?dtoverlay=uart2-pi5', line: 'dtoverlay=uart2-pi5' }
  tags: gps_pps

- name: Install pps-tools for testing/verification
  apt:
    name: pps-tools
    state: present
  tags: gps_pps
